# Generated by Django 5.2.4 on 2026-08-27 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffpromotion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotionapplication',
            name='committee_decision',
            field=models.CharField(blank=True, choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], max_length=20, null=True),
        ),
    ]
